# Input
input:
  trait: "T2D"
  gwas_raw: "/storage/yangjianLab/sharedata/GWAS_summary/01_Public/01_cojo/DIAMANTE_EUR_T2D_2022_NG.txt"
  gwas: "/storage/yangjianLab/sharedata/GWAS_summary/01_Public/01_cojo/DIAMANTE_EUR_T2D_2022_NG.txt"
  output: "/storage/yangjianLab/guoyazhou/GAMMA_git_data"

script:
  work_path: "/storage/yangjianLab/guoyazhou/GAMMA_git/L2G/MAGIC"
  path: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/scripts"
  
software:
  smr: "/storage/yangjianLab/yangwen/alpha-software/smr/smr-1.3.2-alpha3-linux"
  plink1_9: "/storage/yangjianLab/guoyazhou/software/plink/plink1.90beta/plink_1.90_beta"
  plink2: "/storage/yangjianLab/guoyazhou/software/plink/plink2.00alpha/plink2"
  
environment:
  R_421: "Drugsets_py385"

reference:
  reference_bfile: "/storage/yangjianLab/guoyazhou/data/Reference/UKB_Reference_genotype/genotype_10k_hg38/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38"
  reference_bld: "/storage/yangjianLab/guoyazhou/project_SMR_visualizaiton/script/test_script/run_time_test/bld_format/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38_4Mb"
  reference_all_bim: "/storage/yangjianLab/sharedata/LD_reference/UKB/genotype_10K/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38_chrALL.bim"

gene:
  gencode: "/storage/yangjianLab/qiting/data/annotation/gencode/gencode.v40.GRCh38.gene.annotation.bed"

magic:
  QTL_list: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/data/QTL_data/QTL_list.txt"
  R_functions: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/scripts/R_functions/magic_functions.r"
  CpG_link: "/storage/yangjianLab/qiting/SMR_Cauchy/link/consensus/CpG_consensus_all.link"
  hQTL_link: "/storage/yangjianLab/qiting/SMR_Cauchy/link/consensus/hQTL_consensus_all.link"
  caQTL_link: "/storage/yangjianLab/qiting/SMR_Cauchy/link/consensus/caQTL_consensus_all.link"

